(257/2561) [NOK] language/statements/if/if-stmt-else-fun-strict.js	 norm [pass]	semantics [pass]
(258/2561) [NOK] language/statements/if/if-fun-no-else-strict.js	 norm [pass]	semantics [pass]
(259/2561) [NOK] language/statements/if/if-stmt-else-decl-strict.js	 norm [pass]	semantics [pass]
(261/2561) [NOK] language/statements/if/if-fun-else-fun-strict.js	 norm [pass]	semantics [pass]
(264/2561) [NOK] language/statements/if/if-decl-else-stmt-strict.js	 norm [pass]	semantics [pass]
(274/2561) [NOK] language/statements/if/if-fun-else-stmt-strict.js	 norm [pass]	semantics [pass]
(279/2561) [NOK] language/statements/if/if-decl-no-else-strict.js	 norm [pass]	semantics [pass]
(280/2561) [NOK] language/statements/if/if-decl-else-decl-strict.js	 norm [pass]	semantics [pass]
(297/2561) [NOK] language/statements/function/S13.2.1_A6_T3.js	 norm [pass]	semantics [fail]
	[eval]:391
	let __func;
	    ^
	
	SyntaxError: Identifier '__func' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(318/2561) [NOK] language/statements/function/S14_A2.js	 norm [pass]	semantics [fail]
	[eval]:389
	v1 = typeof f;
	^
	
	ReferenceError: Cannot access 'f' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(329/2561) [NOK] language/statements/function/S14_A3.js	 norm [pass]	semantics [fail]
	[eval]:389
	v1 = typeof __func;
	^
	
	ReferenceError: Cannot access '__func' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(336/2561) [NOK] language/statements/function/S13_A18.js	 norm [pass]	semantics [fail]
	[eval]:389
	v1 = typeof sinx;
	^
	
	ReferenceError: Cannot access 'sinx' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(342/2561) [NOK] language/statements/function/S13.2.2_A16_T1.js	 norm [pass]	semantics [fail]
	[eval]:389
	v1 = typeof __func;
	^
	
	ReferenceError: Cannot access '__func' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(357/2561) [NOK] language/statements/function/S13_A19_T1.js	 norm [pass]	semantics [fail]
	[eval]:412
	let __decl;
	    ^
	
	SyntaxError: Identifier '__decl' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(369/2561) [NOK] language/statements/function/S13_A6_T1.js	 norm [pass]	semantics [fail]
	[eval]:396
	let __func;
	    ^
	
	SyntaxError: Identifier '__func' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(395/2561) [NOK] language/statements/function/S13_A2_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: "#2: typeof __func === 'undefined'. Actual: typeof __func ===function"
	}
	
	Node.js v21.6.2
	
(406/2561) [NOK] language/statements/function/S13.2.2_A15_T1.js	 norm [pass]	semantics [fail]
	[eval]:389
	__obj = new __FACTORY();
	^
	
	ReferenceError: Cannot access '__FACTORY' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(409/2561) [NOK] language/statements/function/S14_A5_T1.js	 norm [pass]	semantics [fail]
	[eval]:405
	let __func;
	    ^
	
	SyntaxError: Identifier '__func' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(416/2561) [NOK] language/statements/function/S13.2.2_A8_T1.js	 norm [pass]	semantics [fail]
	[eval]:395
	   __gunc.prop = arg2;
	   ^
	
	ReferenceError: Cannot access '__gunc' before initialization
	    at new __func ([eval]:395:4)
	    at [eval]:406:14
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(428/2561) [NOK] language/statements/function/S13_A2_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: "#2: typeof __func === 'undefined'. Actual: typeof __func ===function"
	}
	
	Node.js v21.6.2
	
(430/2561) [NOK] language/statements/function/S13_A1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: '#2: typeof __exp__func === "undefined". Actual: typeof __exp__func ===function'
	}
	
	Node.js v21.6.2
	
(437/2561) [NOK] language/statements/function/S13.2.2_A15_T2.js	 norm [pass]	semantics [fail]
	[eval]:390
	__obj = new __FACTORY();
	^
	
	ReferenceError: Cannot access '__FACTORY' before initialization
	    at [eval]:390:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(438/2561) [NOK] language/statements/function/S14_A5_T2.js	 norm [pass]	semantics [fail]
	[eval]:405
	let __func;
	    ^
	
	SyntaxError: Identifier '__func' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(451/2561) [NOK] language/statements/function/S13_A19_T2.js	 norm [pass]	semantics [fail]
	[eval]:414
	   let __decl;
	       ^
	
	SyntaxError: Identifier '__decl' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(468/2561) [NOK] language/statements/function/S13_A6_T2.js	 norm [pass]	semantics [fail]
	[eval]:419
	let __func;
	    ^
	
	SyntaxError: Identifier '__func' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(472/2561) [NOK] language/statements/function/S13_A2_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: "#2: typeof __func === 'undefined'. Actual: typeof __func ===function"
	}
	
	Node.js v21.6.2
	
(496/2561) [NOK] language/statements/function/S13.2.2_A16_T2.js	 norm [pass]	semantics [fail]
	[eval]:389
	v1 = typeof __func;
	^
	
	ReferenceError: Cannot access '__func' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(508/2561) [NOK] language/statements/function/S13.2.2_A16_T3.js	 norm [pass]	semantics [fail]
	[eval]:389
	v1 = typeof __func;
	^
	
	ReferenceError: Cannot access '__func' before initialization
	    at [eval]:389:1
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(516/2561) [NOK] language/statements/function/S13.2.2_A12.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: "#1: var obj = new FACTORY() does not lead to throwing exception. Actual: Exception is ReferenceError: Cannot access 'func' before initialization"
	}
	
	Node.js v21.6.2
	
(533/2561) [NOK] language/statements/labeled/decl-fun-strict.js	 norm [pass]	semantics [pass]
(575/2561) [NOK] language/statements/for/S12.6.3_A11.1_T1.js	 norm [pass]	semantics [tout]
(601/2561) [NOK] language/statements/for/S12.6.3_A11_T1.js	 norm [pass]	semantics [tout]
(605/2561) [NOK] language/statements/for/S12.6.3_A11_T2.js	 norm [pass]	semantics [fail]
	[eval]:407
	               continue nested;
	                        ^^^^^^
	
	SyntaxError: Illegal continue statement: 'nested' does not denote an iteration statement
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(630/2561) [NOK] language/statements/for/S12.6.3_A11.1_T2.js	 norm [pass]	semantics [fail]
	[eval]:407
	               continue nested;
	                        ^^^^^^
	
	SyntaxError: Illegal continue statement: 'nested' does not denote an iteration statement
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(663/2561) [NOK] language/statements/try/S12.14_A9_T4.js	 norm [pass]	semantics [tout]
(666/2561) [NOK] language/statements/try/S12.14_A11_T2.js	 norm [pass]	semantics [tout]
(669/2561) [NOK] language/statements/try/S12.14_A9_T5.js	 norm [pass]	semantics [tout]
(684/2561) [NOK] language/statements/try/S12.14_A10_T2.js	 norm [pass]	semantics [tout]
(702/2561) [NOK] language/statements/try/S12.14_A10_T4.js	 norm [pass]	semantics [tout]
(718/2561) [NOK] language/statements/try/S12.14_A10_T5.js	 norm [pass]	semantics [tout]
(723/2561) [NOK] language/statements/try/S12.14_A9_T2.js	 norm [pass]	semantics [tout]
(730/2561) [NOK] language/statements/try/S12.14_A11_T4.js	 norm [pass]	semantics [tout]
(765/2561) [NOK] language/statements/for-in/S12.6.4_A7_T2.js	 norm [pass]	semantics [fail]
	[eval]:398
	   v2 = erasator_T_1000(__obj, "b");
	   ^
	
	ReferenceError: Cannot access 'erasator_T_1000' before initialization
	    at [eval]:398:4
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(796/2561) [NOK] language/statements/for-in/S12.6.4_A7_T1.js	 norm [pass]	semantics [fail]
	[eval]:399
	   v2 = erasator_T_1000(__obj, "b");
	   ^
	
	ReferenceError: Cannot access 'erasator_T_1000' before initialization
	    at [eval]:399:4
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(799/2561) [NOK] language/statements/continue/line-terminators.js	 norm [pass]	semantics [tout]
(808/2561) [NOK] language/statements/continue/S12.7_A9_T1.js	 norm [pass]	semantics [fail]
	[eval]:408
	            continue FOR;
	                     ^^^
	
	SyntaxError: Illegal continue statement: 'FOR' does not denote an iteration statement
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(813/2561) [NOK] language/statements/continue/12.7-1.js	 norm [pass]	semantics [tout]
(822/2561) [NOK] language/statements/while/S12.6.2_A10.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: '#1: FunctionExpression inside while construction expression allowed but function not declare'
	}
	
	Node.js v21.6.2
	
(909/2561) [NOK] language/expressions/dynamic-import/catch/script-code_FIXTURE.js	 norm [pass]	semantics [fail]
	[eval]:389
	let smoosh;
	    ^
	
	SyntaxError: Identifier 'smoosh' has already been declared
	    at makeContextifyScript (node:internal/vm:123:14)
	    at node:internal/process/execution:98:22
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(965/2561) [NOK] language/expressions/postfix-increment/S11.3.1_A5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(971/2561) [NOK] language/expressions/postfix-increment/S11.3.1_A5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(974/2561) [NOK] language/expressions/postfix-increment/S11.3.1_A6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(996/2561) [NOK] language/expressions/postfix-increment/S11.3.1_A5_T5.js	 norm [pass]	semantics [fail]
	[eval]:407
	   x = v6 + 1;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:407:6)
	    at [eval]:411:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(997/2561) [NOK] language/expressions/postfix-increment/S11.3.1_A5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(1141/2561) [NOK] language/expressions/delete/11.4.1-2-2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'd Expected SameValue(<<false>>, <<true>>) to be true'
	}
	
	Node.js v21.6.2
	
(1158/2561) [NOK] language/expressions/delete/11.4.1-0-1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'delete delete z' }
	
	Node.js v21.6.2
	
(1169/2561) [NOK] language/expressions/delete/non-reference-return-true.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'delete void a.b Expected SameValue(<<false>>, <<true>>) to be true'
	}
	
	Node.js v21.6.2
	
(1179/2561) [NOK] language/expressions/delete/S11.4.1_A2.1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#2: delete new Object() === true' }
	
	Node.js v21.6.2
	
(1214/2561) [NOK] language/expressions/delete/11.4.1-2-5.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'd Expected SameValue(<<false>>, <<true>>) to be true'
	}
	
	Node.js v21.6.2
	
(1239/2561) [NOK] language/expressions/postfix-decrement/S11.3.2_A5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1242/2561) [NOK] language/expressions/postfix-decrement/S11.3.2_A5_T5.js	 norm [pass]	semantics [fail]
	[eval]:407
	   x = v6 - 1;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:407:6)
	    at [eval]:411:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1243/2561) [NOK] language/expressions/postfix-decrement/S11.3.2_A5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1249/2561) [NOK] language/expressions/postfix-decrement/S11.3.2_A5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1260/2561) [NOK] language/expressions/postfix-decrement/S11.3.2_A6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(1337/2561) [NOK] language/expressions/array/11.1.4_5-6-1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'arr.hasOwnProperty("1") !== true' }
	
	Node.js v21.6.2
	
(1340/2561) [NOK] language/expressions/array/11.1.4_4-5-1.js	 norm [pass]	semantics [fail]
	Test262Error: arr.hasOwnProperty("0") !== true
	(Use `node --trace-uncaught ...` to show where the exception was thrown)
	
	Node.js v21.6.2
	
(1352/2561) [NOK] language/expressions/prefix-increment/S11.4.4_A5_T5.js	 norm [pass]	semantics [fail]
	[eval]:407
	   x = v6 + 1;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:407:6)
	    at [eval]:411:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1354/2561) [NOK] language/expressions/prefix-increment/S11.4.4_A5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(1358/2561) [NOK] language/expressions/prefix-increment/S11.4.4_A5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(1360/2561) [NOK] language/expressions/prefix-increment/S11.4.4_A5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(1369/2561) [NOK] language/expressions/prefix-increment/S11.4.4_A6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(1438/2561) [NOK] language/expressions/prefix-decrement/S11.4.5_A5_T5.js	 norm [pass]	semantics [fail]
	[eval]:407
	   x = v6 - 1;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:407:6)
	    at [eval]:411:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1441/2561) [NOK] language/expressions/prefix-decrement/S11.4.5_A5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1445/2561) [NOK] language/expressions/prefix-decrement/S11.4.5_A5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1447/2561) [NOK] language/expressions/prefix-decrement/S11.4.5_A5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1455/2561) [NOK] language/expressions/prefix-decrement/S11.4.5_A6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(1459/2561) [NOK] language/expressions/assignment/11.13.1-1-4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a ReferenceError but got a SyntaxError'
	}
	
	Node.js v21.6.2
	
(1460/2561) [NOK] language/expressions/assignment/S11.13.1_A6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 1' }
	
	Node.js v21.6.2
	
(1462/2561) [NOK] language/expressions/assignment/S11.13.1_A6_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 1' }
	
	Node.js v21.6.2
	
(1467/2561) [NOK] language/expressions/assignment/11.13.1-1-1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a ReferenceError but got a SyntaxError'
	}
	
	Node.js v21.6.2
	
(1472/2561) [NOK] language/expressions/assignment/S11.13.1_A7_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1476/2561) [NOK] language/expressions/assignment/S11.13.1_A5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 2. Actual: undefined' }
	
	Node.js v21.6.2
	
(1481/2561) [NOK] language/expressions/assignment/S11.13.1_A5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: undefined' }
	
	Node.js v21.6.2
	
(1484/2561) [NOK] language/expressions/assignment/S11.13.1_A7_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1494/2561) [NOK] language/expressions/assignment/S11.13.1_A5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: undefined' }
	
	Node.js v21.6.2
	
(1497/2561) [NOK] language/expressions/assignment/S11.13.1_A7_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1500/2561) [NOK] language/expressions/assignment/S11.13.1_A5_T5.js	 norm [pass]	semantics [fail]
	[eval]:406
	   x = v6;
	     ^
	
	ReferenceError: x is not defined
	    at v3 ([eval]:406:6)
	    at [eval]:409:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1510/2561) [NOK] language/expressions/assignment/S11.13.1_A6_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === undefined. Actual: 1' }
	
	Node.js v21.6.2
	
(1513/2561) [NOK] language/expressions/assignment/11.13.1-1-2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a ReferenceError but got a SyntaxError'
	}
	
	Node.js v21.6.2
	
(1515/2561) [NOK] language/expressions/assignment/11.13.1-1-3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a ReferenceError but got a SyntaxError'
	}
	
	Node.js v21.6.2
	
(1525/2561) [NOK] language/expressions/function/scope-name-var-close.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected SameValue(<<outside>>, <<function () {\n' +
	    '   probe = function () {\n' +
	    '      return f;\n' +
	    '   }\n' +
	    '}>>) to be true'
	}
	
	Node.js v21.6.2
	
(1676/2561) [NOK] language/expressions/call/S11.2.3_A3_T2.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 663, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1682/2561) [NOK] language/expressions/call/11.2.3-3_3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'fooCalled Expected SameValue(<<true>>, <<false>>) to be true'
	}
	
	Node.js v21.6.2
	
(1686/2561) [NOK] language/expressions/call/S11.2.3_A3_T3.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 663, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1691/2561) [NOK] language/expressions/call/S11.2.4_A1.4_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: '#1.2: function f_arg() {} f_arg(x,x=1) throw ReferenceError. Actual: Test262Error: #1.1: function f_arg() {} f_arg(x,x=1) throw ReferenceError. Actual: undefined'
	}
	
	Node.js v21.6.2
	
(1700/2561) [NOK] language/expressions/call/S11.2.3_A4_T4.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 663, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1701/2561) [NOK] language/expressions/call/scope-lex-open.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected SameValue(<<function () {\n' +
	    '   let name;\n' +
	    "   name = 'inside';\n" +
	    '   probeInside = function () {\n' +
	    '      return name;\n' +
	    '   }\n' +
	    '}>>, <<outside>>) to be true'
	}
	
	Node.js v21.6.2
	
(1702/2561) [NOK] language/expressions/call/scope-var-open.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected SameValue(<<function () {\n' +
	    '   var name;\n' +
	    '   probeBody = function () {\n' +
	    '      return name;\n' +
	    '   }\n' +
	    '}>>, <<outside>>) to be true'
	}
	
	Node.js v21.6.2
	
(1708/2561) [NOK] language/expressions/call/S11.2.3_A3_T1.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 663, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1711/2561) [NOK] language/expressions/call/S11.2.3_A3_T5.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 663, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1770/2561) [NOK] language/expressions/object/11.1.5_3-3-1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'obj.hasOwnProperty("prop") !== true' }
	
	Node.js v21.6.2
	
(1804/2561) [NOK] language/expressions/object/11.1.5_4-5-1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'obj.hasOwnProperty("prop2") !== true' }
	
	Node.js v21.6.2
	
(1904/2561) [NOK] language/expressions/new/S11.2.2_A3_T2.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 590, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1906/2561) [NOK] language/expressions/new/ctorExpr-fn-ref-before-args-eval.js	 norm [pass]	semantics [fail]
	[eval]:394
	result = new x(x);
	         ^
	
	TypeError: x is not a constructor
	    at [eval]:394:10
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1907/2561) [NOK] language/expressions/new/S11.2.2_A3_T3.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 590, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1909/2561) [NOK] language/expressions/new/ctorExpr-isCtor-after-args-eval.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a TypeError to be thrown but no exception was thrown at all'
	}
	
	Node.js v21.6.2
	
(1910/2561) [NOK] language/expressions/new/ctorExpr-fn-ref-before-args-eval-fn-wrapup.js	 norm [pass]	semantics [fail]
	[eval]:396
	   result = new x(x);
	            ^
	
	TypeError: x is not a constructor
	    at fn ([eval]:396:13)
	    at [eval]:407:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1914/2561) [NOK] language/expressions/new/ctorExpr-isCtor-after-args-eval-fn-wrapup.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a TypeError to be thrown but no exception was thrown at all'
	}
	
	Node.js v21.6.2
	
(1915/2561) [NOK] language/expressions/new/S11.2.2_A4_T4.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 590, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1918/2561) [NOK] language/expressions/new/S11.2.2_A3_T1.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 590, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1920/2561) [NOK] language/expressions/new/S11.2.2_A3_T5.js	 norm [fail]	semantics []
	graphjs2: internal error, uncaught exception:
	          Failure("[ERROR] Attempted to convert an expression into an identifier, but the expression provided does not correspond to a valid identifier.")
	          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
	          Called from Ast__Normalize.normalize_expression in file "lib/ast/normalize.ml", line 590, characters 54-107
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 290, characters 24-50
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 71, characters 23-39
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml" (inlined), line 60, characters 12-45
	          Called from Ast__Normalize.normalize_statement in file "lib/ast/normalize.ml", line 176, characters 24-53
	          Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
	          Called from Ast__Normalize.program in file "lib/ast/normalize.ml", line 53, characters 26-83
	          Called from Dune__exe__Main.main.(fun) in file "bin/main.ml", line 44, characters 25-60
	          Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
	          Called from Dune__exe__Main.main in file "bin/main.ml", line 35, characters 2-1023
	          Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
	          Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 35, characters 37-44
	
(1922/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.1_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x * 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1925/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.11_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 6. Actual: 2' }
	
	Node.js v21.6.2
	
(1928/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.10_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1930/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.10_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 6' }
	
	Node.js v21.6.2
	
(1934/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.9_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 1. Actual: 5' }
	
	Node.js v21.6.2
	
(1936/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.8_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1937/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.6_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1950/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.3_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 5' }
	
	Node.js v21.6.2
	
(1951/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.2_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: '#1: innerX === 2. Actual: 0.6666666666666666'
	}
	
	Node.js v21.6.2
	
(1957/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.1_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 6. Actual: 2' }
	
	Node.js v21.6.2
	
(1973/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.4_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(1976/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.3_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x % 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1977/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.2_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(1981/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.6_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(1983/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.10_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(1986/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.7_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x >> 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(1990/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(1995/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.4_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 3' }
	
	Node.js v21.6.2
	
(2007/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.11_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 6. Actual: 2' }
	
	Node.js v21.6.2
	
(2008/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.6_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2012/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.7_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2014/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.9_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 5' }
	
	Node.js v21.6.2
	
(2015/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.8_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2022/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.4_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2025/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.5_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x - 1;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2033/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.2_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2041/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.1_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 8' }
	
	Node.js v21.6.2
	
(2048/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.3_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2050/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.2_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x / 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2054/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2059/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.9_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2060/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.7_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2061/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.11_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2062/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.11_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 6' }
	
	Node.js v21.6.2
	
(2066/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.8_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2068/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.1_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2069/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.10_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(2073/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.2_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 6' }
	
	Node.js v21.6.2
	
(2074/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.3_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#2: x === 3. Actual: 7' }
	
	Node.js v21.6.2
	
(2085/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.9_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2087/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.7_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 1' }
	
	Node.js v21.6.2
	
(2089/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.6_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 16. Actual: 2' }
	
	Node.js v21.6.2
	
(2090/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.8_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2093/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.10_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(2097/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.3_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2100/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.4_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x + 1;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2108/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.5_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2109/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.11_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2110/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.6_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x << 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2111/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.7_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2119/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.1_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2131/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.4_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(2134/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.5_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 1' }
	
	Node.js v21.6.2
	
(2136/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.7_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2138/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.8_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2139/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.6_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 16. Actual: 2' }
	
	Node.js v21.6.2
	
(2141/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.9_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#2: x === 1. Actual: 5' }
	
	Node.js v21.6.2
	
(2143/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.11_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2149/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.2_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 2. Actual: 6' }
	
	Node.js v21.6.2
	
(2151/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.3_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2160/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.8_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x >>> 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2162/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.9_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2170/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.1_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2171/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2178/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.4_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(2186/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.1_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2187/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.10_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x ^ 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2192/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2199/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.4_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 3. Actual: 2' }
	
	Node.js v21.6.2
	
(2202/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.7_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2204/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.9_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2205/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 16. Actual: 2' }
	
	Node.js v21.6.2
	
(2209/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.11_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2211/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.10_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(2216/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.2_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 6' }
	
	Node.js v21.6.2
	
(2217/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.3_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2231/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.1_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 6. Actual: 2' }
	
	Node.js v21.6.2
	
(2239/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.8_T4.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: 'Expected true but got false' }
	
	Node.js v21.6.2
	
(2242/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.9_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x & 3;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2246/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.5_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(2251/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.4_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2261/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.9_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 1. Actual: 5' }
	
	Node.js v21.6.2
	
(2263/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.7_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2265/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A6.8_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerX === 2. Actual: 1' }
	
	Node.js v21.6.2
	
(2267/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.10_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2270/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.6_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2285/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.2_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2290/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.3_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 2. Actual: 5' }
	
	Node.js v21.6.2
	
(2296/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.11_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 6. Actual: 2' }
	
	Node.js v21.6.2
	
(2300/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.7_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 2. Actual: 16' }
	
	Node.js v21.6.2
	
(2302/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.10_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2307/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.6_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2309/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.8_T1.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2320/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.2_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(2322/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.3_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 2. Actual: 5' }
	
	Node.js v21.6.2
	
(2326/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.11_T5.js	 norm [pass]	semantics [fail]
	[eval]:405
	   x = x | 4;
	     ^
	
	ReferenceError: x is not defined
	    at v5 ([eval]:405:6)
	    at [eval]:408:6
	    at runScriptInThisContext (node:internal/vm:144:10)
	    at node:internal/process/execution:109:14
	    at [eval]-wrapper:6:24
	    at runScript (node:internal/process/execution:92:62)
	    at evalScript (node:internal/process/execution:123:10)
	    at node:internal/main/eval_string:51:3
	
	Node.js v21.6.2
	
(2328/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.1_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: scope.x === 6. Actual: 2' }
	
	Node.js v21.6.2
	
(2341/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A5.5_T3.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error { message: '#1: innerScope.x === 1. Actual: 2' }
	
	Node.js v21.6.2
	
(2345/2561) [NOK] language/expressions/compound-assignment/S11.13.2_A7.4_T2.js	 norm [pass]	semantics [fail]
	[eval]:15
	    throw new Test262Error(message);
	    ^
	
	Test262Error {
	  message: 'Expected a DummyError but got a Test262Error'
	}
	
	Node.js v21.6.2
	
(PASSED 100.0%)	language/statements/with	 failed : 0/0   timeout : 0    time : 6.4349ms
(PASSED 100.0%)	language/statements/empty	 failed : 0/0   timeout : 0    time : 6.2801ms
(PASSED 100.0%)	language/statements/variable	 failed : 0/0   timeout : 0    time : 6.0682ms
(PASSED 100.0%)	language/statements/async-function	 failed : 0/0   timeout : 0    time : 5.8496ms
(PASSED 75.8%)	language/statements/if	 failed : 8/8   timeout : 0    time : 6.0055ms
(PASSED 100.0%)	language/statements/return	 failed : 0/0   timeout : 0    time : 5.7766ms
(PASSED 91.0%)	language/statements/function	 failed : 0/21   timeout : 0    time : 6.1538ms
(PASSED 83.3%)	language/statements/labeled	 failed : 1/1   timeout : 0    time : 5.9062ms
(PASSED 100.0%)	language/statements/throw	 failed : 0/0   timeout : 0    time : 5.9784ms
(PASSED 100.0%)	language/statements/do-while	 failed : 0/0   timeout : 0    time : 6.1012ms
(PASSED 94.0%)	language/statements/for	 failed : 0/2   timeout : 2    time : 6.6214ms
(PASSED 100.0%)	language/statements/switch	 failed : 0/0   timeout : 0    time : 5.9463ms
(PASSED 100.0%)	language/statements/switch/syntax/redeclaration	 failed : 0/0   timeout : 0    time : 6.0923ms
(PASSED 90.5%)	language/statements/try	 failed : 0/0   timeout : 8    time : 7.6257ms
(PASSED 100.0%)	language/statements/expression	 failed : 0/0   timeout : 0    time : 5.8995ms
(PASSED 100.0%)	language/statements/break	 failed : 0/0   timeout : 0    time : 5.9823ms
(PASSED 94.1%)	language/statements/for-in	 failed : 0/2   timeout : 0    time : 6.0547ms
(PASSED 81.2%)	language/statements/continue	 failed : 0/1   timeout : 2    time : 5.9478ms
(PASSED 96.0%)	language/statements/while	 failed : 0/1   timeout : 0    time : 6.0083ms
(PASSED 100.0%)	language/statements/block	 failed : 0/0   timeout : 0    time : 5.9963ms
(PASSED 100.0%)	language/expressions/modulus	 failed : 0/0   timeout : 0    time : 6.1845ms
(PASSED 100.0%)	language/expressions/bitwise-and	 failed : 0/0   timeout : 0    time : 6.0316ms
(PASSED 100.0%)	language/expressions/dynamic-import	 failed : 0/0   timeout : 0    time : 6.2829ms
(PASSED 100.0%)	language/expressions/dynamic-import/namespace	 failed : 0/0   timeout : 0    time : 5.6582ms
(PASSED 0.0%)	language/expressions/dynamic-import/catch	 failed : 0/1   timeout : 0    time : 5.8859ms
(PASSED 100.0%)	language/expressions/dynamic-import/syntax/valid	 failed : 0/0   timeout : 0    time : 6.3062ms
(PASSED 100.0%)	language/expressions/relational	 failed : 0/0   timeout : 0    time : 5.9754ms
(PASSED 100.0%)	language/expressions/less-than	 failed : 0/0   timeout : 0    time : 6.0082ms
(PASSED 100.0%)	language/expressions/concatenation	 failed : 0/0   timeout : 0    time : 6.283ms
(PASSED 100.0%)	language/expressions/unary-plus	 failed : 0/0   timeout : 0    time : 7.7425ms
(PASSED 87.8%)	language/expressions/postfix-increment	 failed : 0/5   timeout : 0    time : 6.0196ms
(PASSED 100.0%)	language/expressions/property-accessors	 failed : 0/0   timeout : 0    time : 6.121ms
(PASSED 100.0%)	language/expressions/logical-and	 failed : 0/0   timeout : 0    time : 6.0131ms
(PASSED 100.0%)	language/expressions/division	 failed : 0/0   timeout : 0    time : 6.19ms
(PASSED 100.0%)	language/expressions/conditional	 failed : 0/0   timeout : 0    time : 6.3415ms
(PASSED 100.0%)	language/expressions/instanceof	 failed : 0/0   timeout : 0    time : 6.0951ms
(PASSED 94.4%)	language/expressions/delete	 failed : 0/5   timeout : 0    time : 6.058ms
(PASSED 87.2%)	language/expressions/postfix-decrement	 failed : 0/5   timeout : 0    time : 6.2582ms
(PASSED 100.0%)	language/expressions/greater-than-or-equal	 failed : 0/0   timeout : 0    time : 6.1534ms
(PASSED 100.0%)	language/expressions/subtraction	 failed : 0/0   timeout : 0    time : 6.1361ms
(PASSED 81.8%)	language/expressions/array	 failed : 0/2   timeout : 0    time : 6.1417ms
(PASSED 83.9%)	language/expressions/prefix-increment	 failed : 0/5   timeout : 0    time : 6.1463ms
(PASSED 100.0%)	language/expressions/does-not-equals	 failed : 0/0   timeout : 0    time : 6.0842ms
(PASSED 100.0%)	language/expressions/in	 failed : 0/0   timeout : 0    time : 6.0888ms
(PASSED 100.0%)	language/expressions/grouping	 failed : 0/0   timeout : 0    time : 6.0344ms
(PASSED 84.4%)	language/expressions/prefix-decrement	 failed : 0/5   timeout : 0    time : 6.0954ms
(PASSED 76.3%)	language/expressions/assignment	 failed : 0/14   timeout : 0    time : 6.5767ms
(PASSED 100.0%)	language/expressions/comma	 failed : 0/0   timeout : 0    time : 6.1054ms
(PASSED 100.0%)	language/expressions/exponentiation	 failed : 0/0   timeout : 0    time : 6.3423ms
(PASSED 95.2%)	language/expressions/function	 failed : 0/1   timeout : 0    time : 5.9763ms
(PASSED 100.0%)	language/expressions/strict-does-not-equals	 failed : 0/0   timeout : 0    time : 6.1205ms
(PASSED 100.0%)	language/expressions/unsigned-right-shift	 failed : 0/0   timeout : 0    time : 6.8195ms
(PASSED 100.0%)	language/expressions/equals	 failed : 0/0   timeout : 0    time : 6.0795ms
(PASSED 100.0%)	language/expressions/logical-not	 failed : 0/0   timeout : 0    time : 6.1169ms
(PASSED 100.0%)	language/expressions/bitwise-xor	 failed : 0/0   timeout : 0    time : 6.0984ms
(PASSED 76.3%)	language/expressions/call	 failed : 5/4   timeout : 0    time : 6.5566ms
(PASSED 100.0%)	language/expressions/greater-than	 failed : 0/0   timeout : 0    time : 6.1136ms
(PASSED 96.2%)	language/expressions/object	 failed : 0/2   timeout : 0    time : 6.0443ms
(PASSED 100.0%)	language/expressions/bitwise-or	 failed : 0/0   timeout : 0    time : 6.1268ms
(PASSED 100.0%)	language/expressions/void	 failed : 0/0   timeout : 0    time : 5.8858ms
(PASSED 100.0%)	language/expressions/less-than-or-equal	 failed : 0/0   timeout : 0    time : 6.0648ms
(PASSED 100.0%)	language/expressions/strict-equals	 failed : 0/0   timeout : 0    time : 6.0531ms
(PASSED 100.0%)	language/expressions/import.meta/syntax	 failed : 0/0   timeout : 0    time : 25.476ms
(PASSED 47.1%)	language/expressions/new	 failed : 5/4   timeout : 0    time : 6.148ms
(PASSED 77.0%)	language/expressions/compound-assignment	 failed : 0/99   timeout : 0    time : 6.2052ms
(PASSED 100.0%)	language/expressions/this	 failed : 0/0   timeout : 0    time : 6.1034ms
(PASSED 100.0%)	language/expressions/bitwise-not	 failed : 0/0   timeout : 0    time : 6.3355ms
(PASSED 100.0%)	language/expressions/logical-or	 failed : 0/0   timeout : 0    time : 7.8973ms
(PASSED 100.0%)	language/expressions/right-shift	 failed : 0/0   timeout : 0    time : 7.3009ms
(PASSED 100.0%)	language/expressions/multiplication	 failed : 0/0   timeout : 0    time : 6.2403ms
(PASSED 100.0%)	language/expressions/unary-minus	 failed : 0/0   timeout : 0    time : 6.2114ms
(PASSED 100.0%)	language/expressions/assignmenttargettype	 failed : 0/0   timeout : 0    time : 6.0441ms
(PASSED 100.0%)	language/expressions/left-shift	 failed : 0/0   timeout : 0    time : 7.1083ms
(PASSED 100.0%)	language/expressions/typeof	 failed : 0/0   timeout : 0    time : 6.1893ms
(PASSED 100.0%)	language/expressions/addition	 failed : 0/0   timeout : 0    time : 6.2052ms

    ==============================
    total : 2561
    ok    : 2351
    error : 19 + 188 (normalization + semantics)
    timeout : 12
    time : 6.2052ms
    ==============================
    
